language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t johnvincentio/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johnvincentio/udemy-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'udemy-docker-react'
  env: 'Udemydockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-971716655829'
  bucket_path: 'udemy-docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secret: "$AWS_SECRET_KEY"
